### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by zachhale**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@zachhale -- Thanks for the PR! Unfortunately, travis is all messed up, so I'm going to do a new PR to fix everything :stuck_out_tongue: 

In the future, can you do branches instead of forks? (I've updated permissions).

**Comment by ryan-roemer** [comment]
Subsumed in #2

**Comment by zachhale** [comment]
@ryan-roemer It was a branch, wasn't it?

**Comment by ryan-roemer** [comment]
@zachhale -- Yes it was. (_sorry, long day..._) I somehow read that as `zachhale:readme-typo`

**Pull request closed without merging**
